### ISSUE TITLE
OpPi3bv1.1_img to OPi3bv2.1.img - Chromium Issue

### ISSUE THREAD

**Issue by Gi-0n** [defencedog/orangepi3b_v2.1#3]
I realized something strange: chromium does not save the session started when you open and close the program, it starts completely reset. It seems that this is due to an overlaid configuration. This path is the one that is overwritten every time chromium is opened
![Captura-de-pantalla-de-2024-09-05-16-24-49](https://github.com/user-attachments/assets/4a038807-ea5e-400e-a6be-b86a3f148f63)

**Comment by defencedog** [comment]
`cd /etc/udev/rules.d` then `cat * | grep chrome` is anything listed there?

**Comment by Gi-0n** [comment]
you can close this, there is a partial solution using chromium's own key manager. thanks
